export const GET_PORTFOLIOS = 'GET_PORTFOLIOS';
export const GET_PORTFOLIO = 'GET_PORTFOLIO';
export const GET_TOP_PORTFOLIOS = 'GET_TOP_PORTFOLIOS';
export const GET_WORK = 'GET_WORK';
export const GET_EDUCATION = 'GET_EDUCATION';
